# permissions for end users to view ocswitches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocswitches-viewer-role
rules:
- apiGroups:
  - oc.ocoperator.com
  resources:
  - ocswitches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oc.ocoperator.com
  resources:
  - ocswitches/status
  verbs:
  - get
